const ErrorCode = {
  SOMETHING_WENT_WRONG: 0,
  VALIDATION_ERROR: 1,
  INVALID_ROLE_PERMISSION: 2,
  INVALID_IMAGE_EXTENSION: 3,
  INVALID_USER: 4,
  IMAGE_TOO_BIG: 5,
  USERNAME_TAKEN: 6,
  INVALID_CREDENTIALS: 7,
  INVALID_AVATAR: 8,
  IMAGE_REQUIRED: 9,
  INVALID_REQUEST_INPUT: 10,
  INVALID_POST: 11,
  INVALID_COMMENT_PARENT: 12,
  USERNAME_TOO_LONG: 13,
};

export default ErrorCode;
