const ErrorCode = {
  SOMETHING_WENT_WRONG: 0,
  VALIDATION_ERROR: 1,
  INVALID_ROLE_PERMISSION: 2,
  INVALID_IMAGE: 3,
  INVALID_USER: 4,
  IMAGE_TOO_BIG: 5,
  USERNAME_TAKEN: 6,
  INVALID_CREDENTIALS: 7,
  INVALID_AVATAR: 8,
};

export default ErrorCode;
