export default {
  MAXIMUM_USER_INVITATIONS: 10,
  DEFAULT_USER_INVITATIONS: 10,
  DAILY_FLAIR_ACTIONS: 5,
  DAILY_BIOGRAPHY_ACTIONS: 5,
  DAILY_FEATURED_ACTIONS: 5,
  VISIT_INACTIVITY_MINUTES_FACTOR: 30,
};
